name: Run Rest assured test cases

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - run: CHeckOut
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "16"
          cache: maven
      - run: mvn clean test
