name: Run Rest assured test cases

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: "16"
          cache: maven
      - name: Run Test Cases Using Maven
        run: mvn clean test
